package com.reserve.vo;

/**
 * LevelMaster generated by hbm2java
 */
public class LevelMaster implements java.io.Serializable {

	private Integer levelId;
	private String levelName;
	private int price;
	private int noOfRows;
	private int noOfseats;

	public LevelMaster() {
	}

	public LevelMaster(String levelName, int price, int noOfRows, int noOfseats) {
		this.levelName = levelName;
		this.price = price;
		this.noOfRows = noOfRows;
		this.noOfseats = noOfseats;
	}
	
	public LevelMaster(int levelId) {
		this.levelId = levelId;
	}

	public Integer getLevelId() {
		return this.levelId;
	}

	public void setLevelId(Integer levelId) {
		this.levelId = levelId;
	}

	public String getLevelName() {
		return this.levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getNoOfRows() {
		return this.noOfRows;
	}

	public void setNoOfRows(int noOfRows) {
		this.noOfRows = noOfRows;
	}

	public int getNoOfseats() {
		return this.noOfseats;
	}

	public void setNoOfseats(int noOfseats) {
		this.noOfseats = noOfseats;
	}

}
