package com.reserve.vo;

import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Integer reservationId;
	private User user;
	private SeatHold hold;
	private Date createdDate;

	public Reservation() {
	}

	@Override
	public String toString() {
		StringBuffer seatsAlloc = new StringBuffer();
		return reservationId + " " + user.getEmail() + " " + hold.toString();
	}

	public Reservation(User user, SeatHold hold, Date createdDate) {
		this.user = user;
		this.hold = hold;
		this.createdDate = createdDate;
	}

	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public SeatHold getHold() {
		return this.hold;
	}

	public void setHold(SeatHold hold) {
		this.hold = hold;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
