package com.reserve.vo;

/**
 * SeatmapId generated by hbm2java
 */
public class SeatMapId implements java.io.Serializable {

	private int level;
	private int showid;
	private int rowid;
	private int seatid;

	public SeatMapId() {
	}

	public SeatMapId(int level, int showid, int rowid, int seatid) {
		this.level = level;
		this.showid = showid;
		this.rowid = rowid;
		this.seatid = seatid;
	}

	@Override
	public String toString() {
		return "L" + level + " R" + rowid + " S" + seatid;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public int getShowid() {
		return this.showid;
	}

	public void setShowid(int showid) {
		this.showid = showid;
	}

	public int getRowid() {
		return this.rowid;
	}

	public void setRowid(int rowid) {
		this.rowid = rowid;
	}

	public int getSeatid() {
		return this.seatid;
	}

	public void setSeatid(int seatid) {
		this.seatid = seatid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeatMapId))
			return false;
		SeatMapId castOther = (SeatMapId) other;

		return (this.getLevel() == castOther.getLevel()) && (this.getShowid() == castOther.getShowid())
				&& (this.getRowid() == castOther.getRowid()) && (this.getSeatid() == castOther.getSeatid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLevel();
		result = 37 * result + this.getShowid();
		result = 37 * result + this.getRowid();
		result = 37 * result + this.getSeatid();
		return result;
	}

}
