package com.reserve.vo;

import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private int statusId;
	private String statusName;
	private Set seatmaps = new HashSet(0);

	public Status() {
	}

	public Status(int statusId, String statusName) {
		this.statusId = statusId;
		this.statusName = statusName;
	}

	public Status(int statusId, String statusName, Set seatmaps) {
		this.statusId = statusId;
		this.statusName = statusName;
		this.seatmaps = seatmaps;
	}

	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public Set getSeatmaps() {
		return this.seatmaps;
	}

	public void setSeatmaps(Set seatmaps) {
		this.seatmaps = seatmaps;
	}

}
