package com.reserve.vo;

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String email;
	private String mobile;
	private Set holds = new HashSet(0);
	private Set reservations = new HashSet(0);

	public User() {
	}

	public User(String email) {
		this.email = email;
	}

	public User(String email, String mobile, Set holds, Set reservations) {
		this.email = email;
		this.mobile = mobile;
		this.holds = holds;
		this.reservations = reservations;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Set getHolds() {
		return this.holds;
	}

	public void setHolds(Set holds) {
		this.holds = holds;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
